### ISSUE TITLE
[Request] can you add to Vlive URL?

### ISSUE THREAD

**Issue by bjrambo** [robindz/VSharp#1]
sometime i need make to link. for twitter and discord.

so i use this way
```cs
string Url = $"https://www.vlive.tv/video/{VliveData.VideoSeq}?channelCode={SMTOWN_CHANNEL_CODE}";
```
can you make to url in Video class?

like this,
```cs
string Url = VliveDataVideo.vliveUrl;
```

**Comment by robindz** [comment]
This feature has been added with the exception of also mentioning the `channelCode` in the url, as this data is not available in the `Video` object.
